### ISSUE TITLE
If an exception is thrown, ok button is disabled

### ISSUE THREAD

**Issue by beothorn** [tgiesselmann/gimp-stable-boy#7]
If there is any exception the OK button is disabled, you need to close the dialog and open again.

![image](https://user-images.githubusercontent.com/410600/205506204-d56e91ea-17c7-4cc0-9cbf-931895bd836d.png)

**Comment by thndrbrrr** [comment]
Thanks, @beothorn. From what I can tell this is due to the way GIMP plugins with the simple option interface are run: hit OK and it runs, once. A successful run will close the dialog, and I can't see a way right now to auto-close the plugin dialog when there's an error. (There's veeeery limited documentation available for writing GIMP plugins.)

Anyways, this will not be a problem with the GTK GUI, which is on the roadmap.
